### ISSUE TITLE
missing deps

### ISSUE THREAD

**Issue by cryptix** [dominictarr/patchdeck#1]
Could you check if package.json is complete?

I had to add `pull-identify-filetype` and `stack` to get the `server.js` running and `electro index.js` seems to depend on a PATH installed `electron`, not sure which module should supply that.

**Comment by dominictarr** [comment]
sorry, electron comes from `electron-prebuilt`. I forgot that one.

**Comment by dominictarr** [comment]
Okay, there where lots of deps to update. this should go alright now.

**Comment by dominictarr** [comment]
lemme know if that works

**Comment by cryptix** [comment]
Okay, electron starts now but the window stays white (besides the menu bar)

The console prints this:

```
Error: Cannot find module 'map-filter-reduce/keys'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/cryptix/patchdeck/node_modules/streamview-links/index.js:8:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```
