### ISSUE TITLE
listens on local ip, connects to 127.0.0.1

### ISSUE THREAD

**Issue by keks** [dominictarr/patchdeck#3]
```
Error: could not connect to sbot
    at /home/keks/src/patchdeck/node_modules/ssb-client/index.js:43:19
    at /home/keks/src/patchdeck/node_modules/secret-stack/index.js:68:24
    at /home/keks/src/patchdeck/node_modules/secret-handshake/secure.js:11:20
    at /home/keks/src/patchdeck/node_modules/pull-handshake/index.js:13:5
    at /home/keks/src/patchdeck/node_modules/pull-handshake/index.js:21:13
    at Function.read.end (/home/keks/src/patchdeck/node_modules/pull-handshake/node_modules/pull-pushable/index.js:38:18)
    at Object.handshake.abort (/home/keks/src/patchdeck/node_modules/pull-handshake/index.js:32:16)
    at abort (/home/keks/src/patchdeck/node_modules/secret-handshake/handshake.js:24:37)
    at Object.cb (/home/keks/src/patchdeck/node_modules/secret-handshake/handshake.js:31:22)
  Error: connect ECONNREFUSED 127.0.0.1:8008
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
```

versus

```
$ ss -ltn
State      Recv-Q Send-Q           Local Address:Port                          Peer Address:Port                    
LISTEN     0      128             134.28.183.211:8008                                     *:*                  
LISTEN     0      128                         :::7777                                    :::*                  
```

**Comment by dominictarr** [comment]
hmm, but arn't those usually the same? is this on the difficult school network?

**Comment by keks** [comment]
It seems to work on my home network, but here it doesn't listen on `134.28.183.211:8008` but on `:::8008`, i.e. all interfaces. I don't know why that is, though.
